dist: trusty
sudo: false

branches:
    only:
      - develop
      - master

language: python

python:
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - 3.7-dev

install: pip install tox-travis

script: tox

matrix:
    allow_failures:
        - python: 3.7-dev
#    fast_finish: true

jobs:
    include:
        - stage: test
          python: 3.6
          env: TOXENV=linting

        - stage: deploy
          python: 3.5
          install: skip
          script: skip
          deploy:
              provider: pypi
              on:
                  branch: master
              distributions: sdist bdist_wheel
              user: jcgoble3
              password:
                  secure: ioGko86/sXPaUhg011LSP3UAKdEMJ3tryVMYO09RzHNXVa36iwzRwvZ9L2uOycXvTJuJGyII6tVSQfMXcNImNMpAkhM27rfFtR0PRn+yuahlO7Cl9DL4eYB1ggwKWZH/ORGu0fQOKxtqEEom9k1o0Ylu9DcJ6JhCNQwW6NtVgB6UCQDQENCoeHegiv1E3hfr+I4fqZ0q89wcSPZ/W24yosgqQx28tmfdudQ4M2UddZsZd4BQFfmhuTBzovAOjgG1VPVSKxS1y14f2wvdfZmjLFNZFmoa4+fTCsCDTDZgcwuVVzhQMBdAa83/rOFECooQI++SnuqFT7CTLKh3mFOJzL0KDorQiKXyQiA7Y59gXmTZVNaguHbJvo+rjmkMd4SJALmFAOHa6kj1tT3hjjHbgt2uSzZtAN59a9Xoijs28EysYn5w155xdtGnluxxC0gvilj6W7vHbzaSnLG9OGVDg/gAXS1KOcseDVY27kxjZZ8oUfEZRsNy95ESBrms2rGyFSVrUn9jnHIHV+KXWy9TprYLaKQw9AtXmCiS8Qu5bTW/JtKYVYi5seUFnDaz1skfR/aYJdiCx/q7wfT4D0Zj58fRLi7ItsdY2TT8WNyNGH9nIZlb0NvZVEd8Y7FpHhEIDA66uXKpADbx3faBZwVgmfdO3YVrzvFkDsy08uu80oA=
